### ISSUE TITLE
Nested drawers

### ISSUE THREAD

**Issue by dannypernik** [tomaszbujnowicz/vanilla-js-drawer#3]
Hi, thank you for this elegant menu solution. Is it possible to nest drawers? For example, open the menu, click on a menu button that opens another menu over the top of the first?

**Comment by tomaszbujnowicz** [comment]
You are welcome ;)
I haven't taken this specific case into consideration when writing the script however I think it might be doable with some custom coding on your end.

**Comment by dannypernik** [comment]
Answered my own question – copy the drawer html section, give it a new id, and set `aria-controls`  equal to the new id on the link that opens the 2nd drawer.
