### ISSUE TITLE
How do you make anchor links work?

### ISSUE THREAD

**Issue by ztsuzuki** [tomaszbujnowicz/vanilla-js-drawer#5]
Thank you for a great program.
There is an a tag for an in-page link in the hamburger menu I created, but when I press that button, the in-page link works and takes me to the specified location, but the hamburger menu does not close.
So I tried setting data-drawer-close to the a tag, but this time the in-page link does not work.
Could you please tell me how to achieve the above?

**Comment by tomaszbujnowicz** [comment]
Thanks for your kind words. That would require some custom work. I would suggest to new data-attribute and modify existing functionality.
